# Generated by Django 4.2.7 on 2023-12-02 12:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("JobBoard", "0002_remove_customuser_resume_userprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="job_opening",
            name="type",
            field=models.CharField(
                choices=[
                    ("permanent contract", "permanent contract"),
                    ("fixed-term", "fixed-term"),
                    ("Internship", "Internship"),
                ],
                default=None,
                max_length=50,
            ),
        ),
        migrations.DeleteModel(
            name="UserProfile",
        ),
    ]
