# Generated by Django 4.2.7 on 2023-12-02 13:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("JobBoard", "0003_job_opening_type_delete_userprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="job_opening",
            name="created_at",
            field=models.DateField(auto_now=True),
        ),
    ]
